# Generated by Django 4.2.5 on 2023-09-16 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('thumbnail_sizes', models.TextField()),
                ('original_link', models.BooleanField(default=False)),
                ('expiring_link', models.BooleanField(default=False)),
                ('link_expiration_seconds', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='UserTierAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_upload_app.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail_200', models.ImageField(blank=True, null=True, upload_to='thumbnails/200/')),
                ('thumbnail_200_link', models.URLField(blank=True, null=True)),
                ('thumbnail_400', models.ImageField(blank=True, null=True, upload_to='thumbnails/400/')),
                ('thumbnail_400_link', models.URLField(blank=True, null=True)),
                ('original_link', models.URLField(blank=True, null=True)),
                ('expiring_link', models.URLField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
