# Generated by Django 4.2.5 on 2023-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_200_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_400_link',
        ),
    ]
