# Generated by Django 4.2.5 on 2023-09-19 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0003_remove_tier_link_expiration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_with_expiring_link',
            field=models.ImageField(blank=True, null=True, upload_to='images/expiring'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='link_expiration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
