# Generated by Django 4.2.5 on 2023-09-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0004_image_file_with_expiring_link_alter_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiring_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_link',
        ),
    ]
