# Generated by Django 4.2.5 on 2023-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0005_remove_image_expiring_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='expiring_link',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='original_link',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail_sizes',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
